name: Continuous Integration
on:
  push:
    branches:
      - master
      - actions-*
    tags:
      - v*
  pull_request:
env:
  BUNDLE_CLEAN: "true"
  BUNDLE_PATH: vendor/bundle
  BUNDLE_JOBS: 3
  BUNDLE_RETRY: 3
jobs:
  specs:
    name: ${{ matrix.job }} ruby-${{ matrix.combo.ruby || matrix.ruby }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: falsename: Continuous Integration
      on:
        push:
          branches:
            - main
            - actions-*
          tags:
            - v*
        pull_request:
      env:
        BUNDLE_CLEAN: "true"
        BUNDLE_PATH: vendor/bundle
        BUNDLE_JOBS: 3
        BUNDLE_RETRY: 3
      jobs:
        specs:
          name: ruby-${{ matrix.ruby }} ${{ matrix.appraisal }}
          runs-on: ubuntu-latest
          strategy:
            fail-fast: false
            matrix:
              include:
                - ruby: "ruby"
                  standardrb: true
                - ruby: "ruby"
                  appraisal: "latest"
                - ruby: "3.0"
                - ruby: "2.7"
                - ruby: "2.5"
          env:
            BUNDLE_GEMFILE: ${{ matrix.gemfile }}
          steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up Ruby ${{ matrix.ruby }}
              uses: ruby/setup-ruby@v1
              with:
                ruby-version: ${{ matrix.ruby }}
            - name: Setup bundler
              if: matrix.bundler != ''
              run: |
                gem uninstall bundler --all
                gem install bundler --no-document --version ${{ matrix.bundler }}
            - name: Set Appraisal bundle
              if: matrix.appraisal != '' && matrix.gemfile == ''
              run: |
                echo "using gemfile gemfiles/${{ matrix.appraisal }}.gemfile"
                bundle config set gemfile "gemfiles/${{ matrix.appraisal }}.gemfile"
                cat gemfiles/${{ matrix.appraisal }}.gemfile
            - name: Install bundle
              run: |
                bundle update
            - name: Run specs
              run:  bundle exec rake spec
            - name: Run standardrb
              if:   matrix.standardrb == true
              run:  bundle exec rake standard

      matrix:
        combo:
          - ruby: "3.0"
          - ruby: "2.7"
          - ruby: "2.6"
          - ruby: "2.5"
        job: [ rspec ]
        include:
          - job: "standardrb"
            ruby: "2.7"
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set up Ruby ${{ matrix.combo.ruby || matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.combo.ruby || matrix.ruby }}
      - name: setup bundler
        run:  bundle update
      - name: specs
        if:   matrix.job == 'rspec'
        run:  bundle exec rake spec
      - name: standardrb
        if:   matrix.job == 'standardrb'
        run:  bundle exec rake standard
